allow syncing from project config
viash-io/viash-actions pull request #31
Opened 2024-06-28 13:00 UTC by rcannood

2024-07-03 12:07 UTC, DriesSchaumont requested changes

2024-07-03 13:05 UTC, rcannood commented on project/sync-and-cache/action.yml
> +          done
Both work:

```bash
variable="foo
bar
zing
dong
dang"

echo "# ATTEMPT 1:"
echo "$variable" | \
  while read line; do
    echo "line1: $line"
  done
```

    # ATTEMPT 1:
    line1: foo
    line1: bar
    line1: zing
    line1: dong
    line1: dang

```bash
echo "# ATTEMPT 2:"
while read line; do
  echo "line2: $line"
done <<< "$variable"
```

    # ATTEMPT 2:
    line2: foo
    line2: bar
    line2: zing
    line2: dong
    line2: dang

though I think I prefer the first option, especially if there are more pipes involved (`echo ... | while ... done | md5sum | awk ...`)

2024-07-03 13:11 UTC, rcannood commented on project/sync-and-cache/action.yml
> +        yq e '.info.test_resources[] | "{type: " + (.type // "s3") + ", path: " + .path + ", dest: " + .dest + "}"' "${{ inputs.project_config }}" >> $GITHUB_OUTPUT
Added info to the docs!

2024-07-03 13:11 UTC, rcannood commented on project/sync-and-cache/action.yml
> +        echo "EOF" >> $GITHUB_OUTPUT
Fixed!

2024-07-04 06:14 UTC, DriesSchaumont approved these changes
LGTM!

2024-07-04 06:19 UTC, merged